PROJECT_NAME = "Bakuran POS System Draft#1"
PROJECT_DESCRIPTION = "First Draft of Bakuran POS System"
TARGET_STACK = "react_fastapi_sqlite"
FRONTEND_TEMPLATE = "operational_desk"
AUTH_PROFILE = "disabled"
EXPORT_STATUS = "complete"
MODULES = [
  "business.attendance",
  "business.cash_register",
  "business.categories",
  "business.customers",
  "business.discounts",
  "business.employees",
  "business.inventory",
  "business.kitchen_queue",
  "business.menu",
  "business.orders",
  "business.payments",
  "business.pos",
  "business.products",
  "business.purchasing",
  "business.receipts",
  "business.reorder_levels",
  "business.restaurant_tables",
  "business.sales",
  "business.stock_movements",
  "business.suppliers",
  "business.warehouses",
  "core.api",
  "core.audit_log",
  "core.authentication",
  "core.contacts",
  "core.files",
  "core.health_checks",
  "core.notifications",
  "core.permissions",
  "core.roles",
  "core.search",
  "core.settings",
  "core.users",
  "security.api_security",
  "security.authentication",
  "security.authorization",
  "security.basic",
  "security.csrf_cors",
  "security.file_handling",
  "security.logging_audit",
  "security.rate_limiting",
  "security.secrets_configuration",
  "security.secure_development",
  "security.security_headers",
  "security.session_management",
  "security.standard",
  "security.validation"
]
CAPABILITY_NAMES = [
  "Attendance",
  "Cash Register",
  "Product Categories",
  "Customers",
  "Discounts",
  "Employees",
  "Inventory Management",
  "Kitchen Queue",
  "Restaurant Menu",
  "Orders",
  "Payments",
  "Point of Sale",
  "Products",
  "Purchasing",
  "Receipts",
  "Reorder Levels",
  "Restaurant Tables",
  "Sales",
  "Stock Movements",
  "Suppliers",
  "Warehouses",
  "API",
  "Audit Logging",
  "Authentication",
  "Contacts",
  "Files",
  "Health Checks",
  "Notifications",
  "Permissions",
  "Roles",
  "Search",
  "Settings",
  "Users",
  "API Security Risks",
  "Authentication Controls",
  "Authorization",
  "Basic Security Profile",
  "CSRF and CORS",
  "Secure File Handling",
  "Security Logging and Audit",
  "Rate Limiting and Anti-automation",
  "Secrets and Configuration",
  "Secure Software Development",
  "Security Headers",
  "Session Management",
  "Standard Security Profile",
  "Validation and Business Logic Security"
]
WORKFLOWS = [
  "Kitchen Ticket",
  "Order to Cash",
  "POS Transaction",
  "Purchase Cycle",
  "Restaurant Service",
  "Stock Receipt"
]
